services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_TYPE: release
        COMPILER: dmd
    hostname: backend
    ports:
      - "9999:9999"
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    networks:
      - payment-processor

networks:
  payment-processor:
    external: true
